#!/bin/sh

product=website
repo=/usr/local/git/pub/$product.git
web=~www/apache24/data

unset GIT_DIR
cd $HOME/$product \
	&& git pull \
	&& git --git-dir=$repo --work-tree=$web checkout -f master -- \
		index.html \
		7.1.11.53086.html \
	&& git --git-dir=$repo push
