#!/bin/sh

product=website
repo=/usr/local/git/pub/$product.git
web=~www/apache24/data

git --git-dir=$repo --work-tree=$web checkout -f master -- \
		index.html \
		7.2.2.54709.html \
		7.2.3.54856.html \
	&& git --git-dir=$repo push -f
