#!/bin/sh

product=website
repo=/usr/local/git/pub/$product.git
web=~www/apache24/data

git --git-dir=$repo --work-tree=$web checkout -f master -- \
		index.html \
		7.1.13.53452.html \
		7.1.14.53676.html \
		7.1.13.53713.html \
	&& git --git-dir=$repo push -f
